use super::*;

pub(super) fn workspace_base_routes() -> axum::Router<RouteState> {
    axum::Router::new()
        .route(
            "/api/workspaces",
            get(list_workspaces).post(create_workspace),
        )
        .route(
            "/api/workspaces/:id",
            delete(delete_workspace).get(get_workspace),
        )
        .route(
            "/api/workspaces/:id/harness_container",
            get(get_workspace_harness_container),
        )
        .route(
            "/api/workspaces/:id/harness_container/ensure",
            post(ensure_workspace_harness_container),
        )
        .route(
            "/api/workspaces/:id/harness_container/stop",
            post(stop_workspace_harness_container),
        )
        .route(
            "/api/workspaces/:id/active_snapshot",
            get(get_workspace_active_snapshot),
        )
        .route(
            "/api/workspaces/:id/active_heads",
            get(get_workspace_active_heads),
        )
        .route(
            "/api/workspaces/:id/agent_work",
            get(get_workspace_agent_work),
        )
        .route("/api/workspaces/:id/work", get(list_workspace_work))
        .route("/api/workspaces/:id/work/:work_id", get(get_workspace_work))
        .route(
            "/api/workspaces/:id/work/:work_id/context",
            get(get_workspace_work_context),
        )
        .route(
            "/api/workspaces/:id/work/:work_id/evidence",
            get(get_workspace_work_evidence),
        )
        .route(
            "/api/workspaces/:id/work/:work_id/report",
            get(get_workspace_work_report),
        )
        .route(
            "/api/workspaces/:id/work/:work_id/timeline",
            get(get_workspace_work_timeline),
        )
        .route(
            "/api/workspaces/:id/active_snapshot/stream",
            get(workspace_active_snapshot_stream_ws),
        )
        .route(
            "/api/workspaces/:id/stream",
            get(workspace_active_snapshot_stream_ws),
        )
        .route(
            "/api/workspaces/:id/vcs/stream",
            get(workspace_vcs_stream_ws),
        )
        .route(
            "/api/workspaces/:id/completions/files",
            get(workspace_file_completions),
        )
}
