use ctx_client::BlobUploadResp;
use ts_rs::TS;

use crate::*;

pub fn typescript_declarations() -> String {
    let mut out = String::from("// Generated by ctx-desktop-ipc. Do not edit by hand.\n\n");
    push_decl::<BlobUploadResp>(&mut out);
    push_decl::<DesktopConnectionKind>(&mut out);
    push_decl::<DesktopConnectionIntent>(&mut out);
    push_decl::<DesktopRemoteDaemonUpdateState>(&mut out);
    push_decl::<DesktopConnectionInfo>(&mut out);
    push_decl::<SshConnectReq>(&mut out);
    push_decl::<DesktopSshConnectPollReq>(&mut out);
    push_decl::<DesktopSshConnectJobStatus>(&mut out);
    push_decl::<DesktopDaemonRequest>(&mut out);
    push_decl::<DesktopHttpResponse>(&mut out);
    push_decl::<DesktopRemoteDaemonUpdateReq>(&mut out);
    push_decl::<DesktopRemoteDaemonUpdateResp>(&mut out);
    push_decl::<DesktopLinuxSandboxEnsureResp>(&mut out);
    push_decl::<DesktopLocalLinuxSandboxEnsureReq>(&mut out);
    push_decl::<DesktopRemoteLinuxSandboxEnsureReq>(&mut out);
    push_decl::<DesktopAppUpdateAttemptStageResp>(&mut out);
    push_decl::<DesktopAppUpdateAttemptResp>(&mut out);
    push_decl::<DesktopAppUpdateCheckReq>(&mut out);
    push_decl::<DesktopUpdateChannelSettings>(&mut out);
    push_decl::<DesktopAppUpdateCheckResp>(&mut out);
    push_decl::<DesktopAppUpdateStateResp>(&mut out);
    push_decl::<DesktopAppUpdateApplyReq>(&mut out);
    push_decl::<DesktopAppUpdateApplyResp>(&mut out);
    push_decl::<DesktopAppRestartResp>(&mut out);
    push_decl::<DesktopStorageBatchOp>(&mut out);
    push_decl::<DesktopUiStateResetReason>(&mut out);
    push_decl::<DesktopStorageNotice>(&mut out);
    push_decl::<DesktopStorageGetReq>(&mut out);
    push_decl::<DesktopStorageBatchReq>(&mut out);
    push_decl::<DesktopWebviewSurface>(&mut out);
    push_decl::<DesktopWebviewRecoveryTriggerKind>(&mut out);
    push_decl::<DesktopWebviewRecoveryAction>(&mut out);
    push_decl::<DesktopWebviewRecoveryDaemonHealth>(&mut out);
    push_decl::<DesktopWebviewRecoverySuppressionReason>(&mut out);
    push_decl::<DesktopWebviewRecoveryIncident>(&mut out);
    push_decl::<DesktopWebviewRecoveryHeartbeatReq>(&mut out);
    push_decl::<DesktopWebviewRecoveryFaultKind>(&mut out);
    push_decl::<DesktopWebviewRecoveryFaultReq>(&mut out);
    push_decl::<DesktopWebviewRecoveryWindowAutomationSnapshot>(&mut out);
    push_decl::<DesktopWebviewRecoveryAutomationSnapshot>(&mut out);
    push_decl::<DesktopDeepLinkToken>(&mut out);
    push_decl::<DesktopSshHost>(&mut out);
    push_decl::<DesktopSshTestReq>(&mut out);
    push_decl::<DesktopRemotePrewarmReq>(&mut out);
    push_decl::<DesktopSshPathReq>(&mut out);
    push_decl::<DesktopSshPathEntry>(&mut out);
    push_decl::<DesktopGitBranchReq>(&mut out);
    push_decl::<DesktopGitCloneReq>(&mut out);
    push_decl::<DesktopEditorTarget>(&mut out);
    push_decl::<DesktopEditorSettings>(&mut out);
    push_decl::<DesktopOpenFileReq>(&mut out);
    push_decl::<DesktopOpenPathReq>(&mut out);
    push_decl::<DesktopReadBinaryFileResp>(&mut out);
    push_decl::<DesktopSaveTextFileReq>(&mut out);
    push_decl::<DesktopOpenExternalUrlReq>(&mut out);
    push_decl::<DesktopRestartLocalDaemonReq>(&mut out);
    push_decl::<DesktopUploadBlobReq>(&mut out);
    push_decl::<DesktopCodexLoginRelayReq>(&mut out);
    push_decl::<DesktopMenuItemStateUpdate>(&mut out);
    push_decl::<DesktopSetMenuStateReq>(&mut out);
    push_decl::<DesktopSetOpenWorkspacesReq>(&mut out);
    push_decl::<DesktopOpenWorkspaceInNewWindowReq>(&mut out);
    push_decl::<DesktopRecordWorkspaceVisitReq>(&mut out);
    push_decl::<DesktopWorkbenchRouteTask>(&mut out);
    push_decl::<DesktopRecordWorkbenchRouteReq>(&mut out);
    push_decl::<DesktopTaskRoutePayload>(&mut out);
    push_decl::<DesktopTaskRouteAckReq>(&mut out);
    push_decl::<DesktopDockRecentLocalWorkspace>(&mut out);
    push_decl::<DesktopSetDockRecentLocalWorkspacesReq>(&mut out);
    push_decl::<DesktopTitlebarColor>(&mut out);
    push_decl::<DesktopSetWindowTitleReq>(&mut out);
    push_decl::<DesktopNotificationPermission>(&mut out);
    push_decl::<DesktopNotificationKind>(&mut out);
    push_decl::<DesktopShowSystemNotificationReq>(&mut out);
    push_decl::<DesktopSyncWorkspaceAttentionReq>(&mut out);
    if out.ends_with("\n\n") {
        out.pop();
    }
    out
}

fn push_decl<T: TS>(out: &mut String) {
    out.push_str("export ");
    out.push_str(&T::decl());
    out.push_str("\n\n");
}
